
export const FETCH_COVID_DATA_REQUEST = "FETCH_COVID_DATA_REQUEST";
export const FETCH_COVID_DATA_SUCCESS = "FETCH_COVID_DATA_SUCCESS";
export const FETCH_COVID_DATA_FAILURE = "FETCH_COVID_DATA_FAILURE";
export const FETCH_STATE_COVID_DATA_REQUEST="FETCH_STATE_COVID_DATA_REQUEST";
export const FETCH_STATE_COVID_DATA_SUCCESS="FETCH_STATE_COVID_DATA_SUCCESS";
export const FETCH_STATE_COVID_DATA_FAILURE="FETCH_STATE_COVID_DATA_FAILURE";
